# Generated by Django 5.0.2 on 2024-02-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebook',
            options={'ordering': ('surname',)},
        ),
    ]
